# Generated by Django 5.1.3 on 2024-12-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('oc_name', models.CharField(max_length=50)),
                ('creator', models.CharField(max_length=50)),
                ('media', models.CharField(max_length=70)),
                ('lore_summary', models.CharField(max_length=100)),
                ('reference_link', models.CharField(max_length=100)),
                ('creator_remarks', models.CharField(max_length=100)),
            ],
        ),
    ]
