# Generated by Django 5.1.3 on 2024-12-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_record_lore_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='creator_remarks',
            field=models.TextField(default='N/A', max_length=100),
        ),
    ]
